# Generated by Django 4.2.17 on 2025-01-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
        migrations.RenameIndex(
            model_name='variation',
            new_name='Products_va_id_a9e9e1_idx',
            old_name='Products_va_id_4e1a24_idx',
        ),
    ]
